[build]
builder = "nixpacks"
buildCommand = "bun run build"

[deploy]
startCommand = "bun run start"
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/"
healthcheckTimeout = 30

[deploy.env]
NODE_ENV = "production"
PORT = "3090"